# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [7]:
import numpy as np

2. Create a null vector of size 10 

In [8]:
arr = np.zeros((10))

3. Create a vector with values ranging from 10 to 49

In [9]:
rng = np.arange(10,49)

4. Find the shape of previous array in question 3

In [10]:
rng.shape

(39,)

5. Print the type of the previous array in question 3

In [11]:
rng.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [12]:
print(np.__version__)
print(np.show_config())

1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [13]:
print(rng.ndim)

1


8. Create a boolean array with all the True values

In [14]:
boolean = np.ones((10),dtype=bool)

9. Create a two dimensional array




In [15]:
twoDim = np.zeros((10,10))
print(twoDim.ndim)

2


10. Create a three dimensional array



In [16]:
threedim = np.zeros((10,10,10))
print(threedim.ndim)

3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [17]:
reverse = np.random.randn((10))
print(reverse)
reverse = np.flip(reverse)
print(reverse)

[-1.17456279  0.19208292 -0.17073257 -0.367461   -0.01719167  0.49086572
  0.5129774  -1.00395749  0.39687186 -0.14232323]
[-0.14232323  0.39687186 -1.00395749  0.5129774   0.49086572 -0.01719167
 -0.367461   -0.17073257  0.19208292 -1.17456279]


12. Create a null vector of size 10 but the fifth value which is 1 

In [18]:
nullVector = np.array([1 if x == 4 else 0 for x in range(10)])
print(nullVector)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [19]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [20]:
arr = np.array([1,2,3,4,5],dtype=float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [21]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [22]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 == arr2
print(arr3)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [23]:
odd = np.arange(0,10)
print(odd[odd % 2 != 0])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [24]:
odd[odd % 2 != 0] = -1
print(odd)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [25]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [26]:
twoD = np.ones((4,4))
twoD[1:-1,1:-1] = 0
print(twoD)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [27]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])
arr2d = np.where(arr2d == 5,12,arr2d)
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [28]:
arr3d = np.array([
    [
        [1, 2, 3], 
        [4, 5, 6]
    ], 
    [
        [7, 8, 9], 
        [10, 11, 12]
    ]
])
arr3d[0][0] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [29]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [30]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[1][1]

[[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [31]:
arr2d = np.arange(0,10).reshape((2,5))
print(arr2d)
arr2d[:,2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
rand = np.random.randn((100)).reshape((10,10))
print(f"Minimun Value {np.amin(rand)}")
print(f"Maximum Value {np.amax(rand)}")

Minimun Value -2.3611968126483003
Maximum Value 1.7458451276334497


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Common Elements are : {np.intersect1d(a,b)}")

Common Elements are : [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [34]:
np.searchsorted(a, np.intersect1d(a, b))

array([1, 5])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('==================================================')
print(data[names != 'Will'])

[[-1.50243958e+00 -1.22343212e+00  3.16359861e-01 -1.07110735e+00]
 [ 5.92994546e-01 -1.53202880e+00  2.01109659e-01 -5.04512923e-01]
 [ 8.97123231e-01  2.20109716e+00 -7.06983141e-01 -1.76918509e+00]
 [-1.44458825e+00 -3.22886974e-01  3.55301258e-01 -2.49175392e-01]
 [-1.06212122e+00 -6.57438742e-04  9.67022218e-02  3.28317063e-01]
 [ 8.78141851e-01 -3.04030242e-01  9.33133512e-01 -8.06064345e-01]
 [ 4.01213227e-01 -7.31609932e-01  1.36351867e-02 -1.18297937e+00]]
[[-1.50243958 -1.22343212  0.31635986 -1.07110735]
 [ 0.59299455 -1.5320288   0.20110966 -0.50451292]
 [-1.44458825 -0.32288697  0.35530126 -0.24917539]
 [ 0.87814185 -0.30403024  0.93313351 -0.80606435]
 [ 0.40121323 -0.73160993  0.01363519 -1.18297937]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [36]:
print(data)
print('==================================================')
mask = (names != 'Will') & (names!= 'Joe')
print(data[mask])

[[-1.50243958e+00 -1.22343212e+00  3.16359861e-01 -1.07110735e+00]
 [ 5.92994546e-01 -1.53202880e+00  2.01109659e-01 -5.04512923e-01]
 [ 8.97123231e-01  2.20109716e+00 -7.06983141e-01 -1.76918509e+00]
 [-1.44458825e+00 -3.22886974e-01  3.55301258e-01 -2.49175392e-01]
 [-1.06212122e+00 -6.57438742e-04  9.67022218e-02  3.28317063e-01]
 [ 8.78141851e-01 -3.04030242e-01  9.33133512e-01 -8.06064345e-01]
 [ 4.01213227e-01 -7.31609932e-01  1.36351867e-02 -1.18297937e+00]]
[[-1.50243958 -1.22343212  0.31635986 -1.07110735]
 [-1.44458825 -0.32288697  0.35530126 -0.24917539]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [37]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 3.36779628 12.68310658 10.82015256]
 [10.95636226 12.23167379 10.2295155 ]
 [11.82050806  3.73689192  4.53233171]
 [13.1177243   4.045887    5.77601227]
 [ 2.77124263 10.23163904  3.94159106]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [38]:
rand_arr2 = np.random.uniform(1,16, size=(2,2,4))
print(rand_arr2)

[[[10.26098231  7.26432151  4.29284919  6.12791871]
  [ 6.5483879  15.43453118  9.46499286  2.0286793 ]]

 [[ 1.37422785  3.1711639   5.19706279  2.5201462 ]
  [ 4.05457753  3.08623326  5.58602714  7.18256825]]]


33. Swap axes of the array you created in Question 32

In [39]:
print("Original Array")
print(rand_arr2)
print("Swapped Axes")
print(np.swapaxes(rand_arr2, 2, 0))

Original Array
[[[10.26098231  7.26432151  4.29284919  6.12791871]
  [ 6.5483879  15.43453118  9.46499286  2.0286793 ]]

 [[ 1.37422785  3.1711639   5.19706279  2.5201462 ]
  [ 4.05457753  3.08623326  5.58602714  7.18256825]]]
Swapped Axes
[[[10.26098231  1.37422785]
  [ 6.5483879   4.05457753]]

 [[ 7.26432151  3.1711639 ]
  [15.43453118  3.08623326]]

 [[ 4.29284919  5.19706279]
  [ 9.46499286  5.58602714]]

 [[ 6.12791871  2.5201462 ]
  [ 2.0286793   7.18256825]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [40]:
arr = np.random.uniform(0,20, size=(10))
arr = arr.astype('int32') 
arr =np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[4 1 2 4 1 3 2 3 2 3]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
arr = np.random.uniform(0,20, size=(10))
arr1 = np.random.uniform(0,20, size=(10))
newArr = np.maximum(arr,arr1)
print(f"Array 1 : {arr}")
print(f"Array 2 : {arr1}")
print(f"New Array : {newArr}")


Array 1 : [12.56454229  1.5720844   5.48842034 12.36008041 19.58192659  7.91420215
 16.63851071 19.95912663 19.67812417  1.73767065]
Array 2 : [12.70709346  4.56782749 12.50106395 12.80798259  9.83234451 13.65867591
 11.66904119 19.08537693 16.55076959 14.57329097]
New Array : [12.70709346  4.56782749 12.50106395 12.80798259 19.58192659 13.65867591
 16.63851071 19.95912663 19.67812417 14.57329097]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [42]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [43]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:
sampleArray = np.array([
    [34,43,73],
    [82,22,12],
    [53,94,66]
])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 2, axis=1)
sampleArray = np.insert(sampleArray, 2, newColumn, axis=1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [45]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [46]:
arr = np.random.uniform(1,20,size=(4,5))
arr = arr.astype('int32')
print(arr.cumsum())

[  1  18  35  40  42  54  64  78  86  98 111 123 128 145 157 159 165 183
 190 198]
